name: 'Kivy App to APK'
description: 'Convert Kivy app to APK'

on:
  push:
    branches: 
      - main  # Change to the branch you want to trigger on
  pull_request:
    branches:
      - main  # Optionally trigger on pull requests to this branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          architecture: x64
          python-version: 3.8

      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV

      - name: Prepare virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          echo "Using Python==$(python --version)"
        shell: bash

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            wget
        shell: bash

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
          unzip sdk-tools-linux-3859397.zip -d $HOME/Android/Sdk/
          yes | $HOME/Android/Sdk/tools/bin/sdkmanager --licenses
          $HOME/Android/Sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-30"
        shell: bash

      - name: Update PATH
        run: |
          echo "PATH=$PATH:$HOME/Android/Sdk/tools/bin:$HOME/Android/Sdk/platform-tools" >> $GITHUB_ENV

      - name: Install Python packages
        run: |
          source venv/bin/activate
          python3 -m pip install --upgrade \
            Cython==0.29.33 \
            buildozer
        shell: bash

      - name: Install requirements in requirements.txt if it exists
        run: |
          if [ -f requirements.txt ]; then
            source venv/bin/activate
            python3 -m pip install -r requirements.txt
          fi
        shell: bash

      - name: Build with Buildozer
        run: |
          source venv/bin/activate
          buildozer android debug
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
